/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WinesSearchRouteImport } from './routes/wines/search'
import { Route as WinesAddRouteImport } from './routes/wines/add'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WinesSearchRoute = WinesSearchRouteImport.update({
  id: '/wines/search',
  path: '/wines/search',
  getParentRoute: () => rootRouteImport,
} as any)
const WinesAddRoute = WinesAddRouteImport.update({
  id: '/wines/add',
  path: '/wines/add',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/wines/add': typeof WinesAddRoute
  '/wines/search': typeof WinesSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/wines/add': typeof WinesAddRoute
  '/wines/search': typeof WinesSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/wines/add': typeof WinesAddRoute
  '/wines/search': typeof WinesSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/register' | '/wines/add' | '/wines/search'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register' | '/wines/add' | '/wines/search'
  id: '__root__' | '/' | '/login' | '/register' | '/wines/add' | '/wines/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  WinesAddRoute: typeof WinesAddRoute
  WinesSearchRoute: typeof WinesSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wines/search': {
      id: '/wines/search'
      path: '/wines/search'
      fullPath: '/wines/search'
      preLoaderRoute: typeof WinesSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wines/add': {
      id: '/wines/add'
      path: '/wines/add'
      fullPath: '/wines/add'
      preLoaderRoute: typeof WinesAddRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  WinesAddRoute: WinesAddRoute,
  WinesSearchRoute: WinesSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
